//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestion_casos.Infrastructure.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("gestion_casos.Infrastructure.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API key invalid..
        /// </summary>
        public static string API_KEY_INVALID {
            get {
                return ResourceManager.GetString("API_KEY_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API key not found..
        /// </summary>
        public static string API_KEY_NOT_FOUND {
            get {
                return ResourceManager.GetString("API_KEY_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/json.
        /// </summary>
        public static string APPLICATION_CONTENT_TYPE {
            get {
                return ResourceManager.GetString("APPLICATION_CONTENT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error API de Jira:.
        /// </summary>
        public static string ERROR_API_JIRA {
            get {
                return ResourceManager.GetString("ERROR_API_JIRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato de fecha no reconocido..
        /// </summary>
        public static string ERROR_FORMATO_DE_FECHA_INVALIDO {
            get {
                return ResourceManager.GetString("ERROR_FORMATO_DE_FECHA_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al llamar a la API:.
        /// </summary>
        public static string ERROR_LLAMADO_API {
            get {
                return ResourceManager.GetString("ERROR_LLAMADO_API", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en base de datos:.
        /// </summary>
        public static string PERSISTENCIA_EXCEPTION {
            get {
                return ResourceManager.GetString("PERSISTENCIA_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReporteSolicitudException.
        /// </summary>
        public static string REPORTE_SOLICITUD_EXCEPTION {
            get {
                return ResourceManager.GetString("REPORTE_SOLICITUD_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El adjunto no puede ser nulo.
        /// </summary>
        public static string VALIDACION_ADJUNTO {
            get {
                return ResourceManager.GetString("VALIDACION_ADJUNTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La instancia de mongo cliente no puede ser nula..
        /// </summary>
        public static string VALIDACION_CLIENTE {
            get {
                return ResourceManager.GetString("VALIDACION_CLIENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La configuración para mongodb no puede ser nula..
        /// </summary>
        public static string VALIDACION_CONFIG {
            get {
                return ResourceManager.GetString("VALIDACION_CONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La entidad no puede ser nula.
        /// </summary>
        public static string VALIDACION_ENTIDAD {
            get {
                return ResourceManager.GetString("VALIDACION_ENTIDAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No fue posible actualizar la entidad, faltan asignaciones..
        /// </summary>
        public static string VALIDACION_ENTIDAD_ACTUALIZAR {
            get {
                return ResourceManager.GetString("VALIDACION_ENTIDAD_ACTUALIZAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La entidad no cumple con todos los criterios, faltan asignaciones..
        /// </summary>
        public static string VALIDACION_ENTIDAD_GUARDAR {
            get {
                return ResourceManager.GetString("VALIDACION_ENTIDAD_GUARDAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Id de la entidad no puede ser nula o vacía.
        /// </summary>
        public static string VALIDACION_ENTIDAD_ID {
            get {
                return ResourceManager.GetString("VALIDACION_ENTIDAD_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizar:.
        /// </summary>
        public static string VALIDACION_ERROR_ACTUALIZAR {
            get {
                return ResourceManager.GetString("VALIDACION_ERROR_ACTUALIZAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en base de datos:.
        /// </summary>
        public static string VALIDACION_ERROR_EN_LA_BASE_DE_DATOS {
            get {
                return ResourceManager.GetString("VALIDACION_ERROR_EN_LA_BASE_DE_DATOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe la solicitud con Id:.
        /// </summary>
        public static string VALIDACION_ESTADO_SOLICITUD {
            get {
                return ResourceManager.GetString("VALIDACION_ESTADO_SOLICITUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El parámetro payload no puede ser null..
        /// </summary>
        public static string VALIDACION_ESTADO_SOLICITUD_MAPPER {
            get {
                return ResourceManager.GetString("VALIDACION_ESTADO_SOLICITUD_MAPPER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La plantilla no existe..
        /// </summary>
        public static string VALIDACION_EXISTENCIA_PLANTILLA {
            get {
                return ResourceManager.GetString("VALIDACION_EXISTENCIA_PLANTILLA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Fecha de la actualizacion de la solicitud no puede estar nulo o vacio.
        /// </summary>
        public static string VALIDACION_FECHA_ACTUALIZACION_SOLICITUD {
            get {
                return ResourceManager.GetString("VALIDACION_FECHA_ACTUALIZACION_SOLICITUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HttpClient ya ha sido creado..
        /// </summary>
        public static string VALIDACION_HTTP {
            get {
                return ResourceManager.GetString("VALIDACION_HTTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre de la base de datos no puede ser nulo o vacío..
        /// </summary>
        public static string VALIDACION_NOMBRE_BASE_DE_DATOS {
            get {
                return ResourceManager.GetString("VALIDACION_NOMBRE_BASE_DE_DATOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El proceso de envío de correo ha fallado..
        /// </summary>
        public static string VALIDACION_NOTIFICACION_CORREO {
            get {
                return ResourceManager.GetString("VALIDACION_NOTIFICACION_CORREO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El proceso de envío de SMS ha fallado..
        /// </summary>
        public static string VALIDACION_NOTIFICACION_SMS {
            get {
                return ResourceManager.GetString("VALIDACION_NOTIFICACION_SMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo obtener la plantilla del servicio de notificación. Código de estado:.
        /// </summary>
        public static string VALIDACION_PLANTILLA_EXCEPTION {
            get {
                return ResourceManager.GetString("VALIDACION_PLANTILLA_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El estatus de la solicitud no puede estar nulo o vacio..
        /// </summary>
        public static string VALIDACION_SOLICITUD_ESTATUS {
            get {
                return ResourceManager.GetString("VALIDACION_SOLICITUD_ESTATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El key de la solicitud no puede estar nulo o vacio..
        /// </summary>
        public static string VALIDACION_SOLICITUD_KEY {
            get {
                return ResourceManager.GetString("VALIDACION_SOLICITUD_KEY", resourceCulture);
            }
        }
    }
}
