//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestion_casos.Infrastructure.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SettingMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("gestion_casos.Infrastructure.Resources.SettingMessages", typeof(SettingMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambio de estado Solicitud a:.
        /// </summary>
        internal static string CAMBIO_ESTADO {
            get {
                return ResourceManager.GetString("CAMBIO_ESTADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comentario.
        /// </summary>
        internal static string COMENTARIO {
            get {
                return ResourceManager.GetString("COMENTARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentario de la solicitud Jira.
        /// </summary>
        internal static string COMENTARIO_JIRA {
            get {
                return ResourceManager.GetString("COMENTARIO_JIRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToEmail.
        /// </summary>
        internal static string CORREO_DESTINO {
            get {
                return ResourceManager.GetString("CORREO_DESTINO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DESTINATARY.
        /// </summary>
        internal static string DESTINATARIO_SMS {
            get {
                return ResourceManager.GetString("DESTINATARIO_SMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enlace.
        /// </summary>
        internal static string ENLACE {
            get {
                return ResourceManager.GetString("ENLACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enlace para ver el detalle de la solicitud.
        /// </summary>
        internal static string ENLACE_SOLICITUD {
            get {
                return ResourceManager.GetString("ENLACE_SOLICITUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estatus al que pasó la solicitud.
        /// </summary>
        internal static string ESTATUS_CAMBIO_SOLICITUD {
            get {
                return ResourceManager.GetString("ESTATUS_CAMBIO_SOLICITUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to estatusSolicitud.
        /// </summary>
        internal static string ESTATUS_SOLICITUD {
            get {
                return ResourceManager.GetString("ESTATUS_SOLICITUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es.
        /// </summary>
        internal static string IDIOMA_PLANTILLA {
            get {
                return ResourceManager.GetString("IDIOMA_PLANTILLA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.Language.
        /// </summary>
        internal static string LENGUAJE_PLANTILLA {
            get {
                return ResourceManager.GetString("LENGUAJE_PLANTILLA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS_MESSAGE.
        /// </summary>
        internal static string MENSAJE_SMS {
            get {
                return ResourceManager.GetString("MENSAJE_SMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre del destinatario del correo.
        /// </summary>
        internal static string NOMBRE_DESTINATARIO {
            get {
                return ResourceManager.GetString("NOMBRE_DESTINATARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nombreIntermediario.
        /// </summary>
        internal static string NOMBRE_INTERMEDIARIO {
            get {
                return ResourceManager.GetString("NOMBRE_INTERMEDIARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.Name.
        /// </summary>
        internal static string NOMBRE_PLANTILLA {
            get {
                return ResourceManager.GetString("NOMBRE_PLANTILLA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.PlatformName.
        /// </summary>
        internal static string NOMBRE_PLATAFORMA {
            get {
                return ResourceManager.GetString("NOMBRE_PLATAFORMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProviderName.
        /// </summary>
        internal static string NOMBRE_PROVEEDOR {
            get {
                return ResourceManager.GetString("NOMBRE_PROVEEDOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to numeroSolicitud.
        /// </summary>
        internal static string NUMERO_SOLICITUD {
            get {
                return ResourceManager.GetString("NUMERO_SOLICITUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de la solicitud de JIRA.
        /// </summary>
        internal static string NUMERO_SOLICITUD_JIRA {
            get {
                return ResourceManager.GetString("NUMERO_SOLICITUD_JIRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.Metadata.
        /// </summary>
        internal static string PLANTILLA_METADATA {
            get {
                return ResourceManager.GetString("PLANTILLA_METADATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS.
        /// </summary>
        internal static string SMS {
            get {
                return ResourceManager.GetString("SMS", resourceCulture);
            }
        }
    }
}
